# Generated by Django 4.2.29 on 2026-04-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagrisk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportanalysis',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
